sylius_ui:
    events:
        sylius.admin.layout.topbar_right:
            blocks:
                admin_notifications:
                    template: '@SynoliaSyliusAdminNotificationPlugin/Notifications/top_bar.html.twig'
                    priority: 11

framework:
    notifier:
        chatter_transports:
            admin_notification: 'adminnotification://TOKEN@default?channel=CHANNEL'

sylius_grid:
    grids:
        synolia_sylius_admin_notification:
            driver:
                name: doctrine/orm
                options:
                    class: '%synolia_sylius_admin_notification.model.admin_notification.class%'
            sorting:
                createdAt: desc
                channel: asc
            limits: [10, 25, 50, 100]
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: true
                    enabled: true
                channel:
                    type: string
                    label: sylius.ui.channel
                    sortable: true
                    enabled: false
                message:
                    type: string
                    label: synolia_sylius_admin_notification.ui.message
                    sortable: true
                    enabled: true
                levelName:
                    type: string
                    label: synolia_sylius_admin_notification.ui.level_name
                    sortable: true
                    enabled: true
                context:
                    type: string
                    label: synolia_sylius_admin_notification.ui.level_name
                    sortable: true
                    enabled: false
            filters:
                channel:
                    type: string
                    label: sylius.ui.channel
                    enabled: true
                    default_value: ~
                levelName:
                    type: string
                    label: synolia_sylius_admin_notification.ui.level_name
                    enabled: true
                    default_value: ~
                message:
                    type: string
                    label: synolia_sylius_admin_notification.ui.message
                    enabled: true
                    default_value: ~
                context:
                    type: string
                    label: synolia_sylius_admin_notification.ui.context
                    enabled: true
                    default_value: ~
            actions:
                item:
                    show:
                        type: show
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
                        label: sylius.ui.delete
                        enabled: true
                        position: 100
                        options: { }
